//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestBurgerManagerAPI.Test.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BestBurgerManagerAPI.Test.Resources.JsonResources", typeof(JsonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;PosId&quot;: 4,
        ///  &quot;Items&quot;: [
        ///    {
        ///      &quot;Id&quot;: 1,
        ///      &quot;Name&quot;: &quot;Burger&quot;,
        ///      &quot;Status&quot;: 1
        ///    }
        ///  ],
        ///  &quot;Status&quot;: 1 
        ///}.
        /// </summary>
        internal static string kitchenOrder {
            get {
                return ResourceManager.GetString("kitchenOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ 
        ///  {
        ///    &quot;PosId&quot;: 1,
        ///    &quot;Items&quot;: [
        ///      {
        ///        &quot;Id&quot;: 1,
        ///        &quot;Name&quot;: &quot;Burger&quot;,
        ///        &quot;KitchenArea&quot;: 1,
        ///        &quot;Status&quot;: 1
        ///      }
        ///    ],
        ///    &quot;Status&quot;: 1 
        ///  },
        ///  {
        ///    &quot;PosId&quot;: 1,
        ///    &quot;Items&quot;: [
        ///      {
        ///        &quot;Id&quot;: 1,
        ///        &quot;Name&quot;: &quot;Fries&quot;,
        ///        &quot;KitchenArea&quot;: 2,
        ///        &quot;Status&quot;: 1
        ///      },
        ///      {
        ///        &quot;Id&quot;: 2,
        ///        &quot;Name&quot;: &quot;Burger&quot;,
        ///        &quot;KitchenArea&quot;: 1,
        ///        &quot;Status&quot;: 1
        ///      }
        ///    ],
        ///    &quot;Status&quot;: 1 
        ///  },
        ///  {
        ///    &quot;PosId&quot;: 1,
        ///    &quot;Items&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string multipleOrders {
            get {
                return ResourceManager.GetString("multipleOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;PosId&quot;: 1,
        ///  &quot;Items&quot;: [
        ///    {
        ///      &quot;Id&quot;: 1,
        ///      &quot;Name&quot;: &quot;Burger&quot;,
        ///      &quot;KitchenArea&quot;: 1,
        ///      &quot;Status&quot;: 1
        ///    }
        ///  ],
        ///  &quot;Status&quot;: 1 
        ///}.
        /// </summary>
        internal static string singleOrder {
            get {
                return ResourceManager.GetString("singleOrder", resourceCulture);
            }
        }
    }
}
